/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book-appointment`; params?: Router.UnknownInputParams; } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/guest-inspo-upload`; params?: Router.UnknownInputParams; } | { pathname: `/manage-portfolio`; params?: Router.UnknownInputParams; } | { pathname: `/my-services`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownInputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/book-appointment`; params?: Router.UnknownOutputParams; } | { pathname: `/complete-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/guest-inspo-upload`; params?: Router.UnknownOutputParams; } | { pathname: `/manage-portfolio`; params?: Router.UnknownOutputParams; } | { pathname: `/my-services`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/book-appointment${`?${string}` | `#${string}` | ''}` | `/complete-profile${`?${string}` | `#${string}` | ''}` | `/guest-inspo-upload${`?${string}` | `#${string}` | ''}` | `/manage-portfolio${`?${string}` | `#${string}` | ''}` | `/my-services${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/signup-2fa-choice${`?${string}` | `#${string}` | ''}` | `/verify-2fa${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/account${`?${string}` | `#${string}` | ''}` | `/tabs/appointments${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/portfolios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/book-appointment`; params?: Router.UnknownInputParams; } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/guest-inspo-upload`; params?: Router.UnknownInputParams; } | { pathname: `/manage-portfolio`; params?: Router.UnknownInputParams; } | { pathname: `/my-services`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownInputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownInputParams; };
    }
  }
}
