/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownInputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TwoFactorSection`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/auth-api`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/auth-types`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/countries-states`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/me-api`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/signup-draft`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/products`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/complete-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/purchases`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Dropdown`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TwoFactorSection`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/auth-api`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/auth-types`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/countries-states`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/me-api`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/signup-draft`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/products`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/complete-profile${`?${string}` | `#${string}` | ''}` | `/purchases${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/signup-2fa-choice${`?${string}` | `#${string}` | ''}` | `/verify-2fa${`?${string}` | `#${string}` | ''}` | `/../components/Dropdown${`?${string}` | `#${string}` | ''}` | `/../components/TwoFactorSection${`?${string}` | `#${string}` | ''}` | `/../lib/auth-api${`?${string}` | `#${string}` | ''}` | `/../lib/auth-types${`?${string}` | `#${string}` | ''}` | `/../lib/countries-states${`?${string}` | `#${string}` | ''}` | `/../lib/me-api${`?${string}` | `#${string}` | ''}` | `/../lib/signup-draft${`?${string}` | `#${string}` | ''}` | `/../contexts/AuthContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/account${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/portfolios${`?${string}` | `#${string}` | ''}` | `/tabs/products${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/complete-profile`; params?: Router.UnknownInputParams; } | { pathname: `/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup-2fa-choice`; params?: Router.UnknownInputParams; } | { pathname: `/verify-2fa`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TwoFactorSection`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/auth-api`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/auth-types`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/countries-states`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/me-api`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/signup-draft`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/portfolios`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/products`; params?: Router.UnknownInputParams; };
    }
  }
}
